
name: Build and Deploy to Firebase Hosting

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install libraries
      run: yarn install
      working-directory: ${{env.working-directory}}
    - name: install firebase
      run: yarn global add firebase-tools  
    - name: deploy
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
